### ISSUE TITLE
Where is software?

### ISSUE THREAD

**Issue by iceberg1369** [embeddedalpha/ProIMU#1]
Is software and firmsare going to be included?

**Comment by embeddedalpha** [comment]
> Is software and firmsare going to be included?

Hi I'm still working on it. As the code will be in Bare-metal Embedded C, it will take some time. Yes the software will be included.

**Comment by iceberg1369** [comment]
Does imu support compassless heading? ( fuse velocity from gps and 6 axis imu)?

**Comment by embeddedalpha** [comment]
Yes. The idea is to use 9 Axis IMU, the MPU9250, and a GNSS module to get the most accurate results.
